name: Perchance Comment Scraper

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly
  workflow_dispatch:      # Manual trigger
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install @octokit/rest node-fetch
        
      - name: Run Scraper
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}
          TARGET_BRANCH: perchance_comments
        run: node .github/scripts/perchance_comment_scraper.js
