name: Perchance Comment Scraper

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  
jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Create package.json
        run: |
          echo '{
            "name": "perchance-scraper",
            "type": "module",
            "dependencies": {
              "@octokit/rest": "^20.0.2",
              "node-fetch": "^3.3.2"
            }
          }' > package.json
          
      - run: npm install
        
      - name: Run Scraper
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}
          TARGET_BRANCH: perchance_comments
        run: node .github/scripts/perchance_comment_scraper.js
