name: Processor

on:
  workflow_dispatch:  # Maintains ability to run manually
  
jobs:
  procss:
    runs-on: ubuntu-latest
    
    # Adds concurrency to prevent simultaneous runs
    concurrency:
      group: scrape-comments
      cancel-in-progress: false    # Prevents new jobs from starting while current one is running
    
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test_processor
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Debug - List files before running script
        run: ls -R ai-character-char/characters/scrape/

      - name: Run Processor
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_ACTIONS }}
          TARGET_BRANCH: test_processor
        run: node .github/scripts/process.js
